### ISSUE TITLE
UnsupportedOperationException -> nth not supported on this type: PersistentArrayMap

### ISSUE THREAD

**Issue by jabley** [FundingCircle/fc4c#50] opened 2018-07-04 15:10 UTC
I'm running 2d4485a.

```sh
> brew install clojure
> git clone git@github.com:FundingCircle/fc4c.git
> pushd fc4c/
> clojure -R:dev -e '(println "deps installed!")'
...
deps installed!
> git show --summary 
commit 2d4485a722a016390cf575b02c3b6fd1d8077be2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 67f019c 86e4d8a
Author: Avi Flax <avi.flax@fundingcircle.com>
Date:   Tue Jul 3 11:03:42 2018 -0400

    Merge pull request #48 from FundingCircle/export-command
    
    New CLI command `export`
> ./wcb 
Now watching clipboard for Structurizr Express diagrams in YAML format. Hit ctrl-c to exit.
UnsupportedOperationException -> nth not supported on this type: PersistentArrayMap
```

The YAML doesn't get reformatted or cleansed as I was expecting.

```sh
> java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
> brew info clojure
clojure: stable 1.9.0.381
The Clojure Programming Language
https://clojure.org
/opt/boxen/homebrew/Cellar/clojure/1.9.0.381 (9 files, 20.9MB) *
  Built from source on 2018-07-04 at 15:15:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/clojure.rb
==> Dependencies
Required: rlwrap ✔
==> Requirements
Required: java >= 1.8 ✔
```

What am I missing?

**Comment by aviflax** [comment] 2018-07-18 19:21
Hi, so sorry, I just saw this — not sure how I missed it! I’ll try to look into this today.

**Comment by aviflax** [comment] 2018-07-27 22:40
I’m terribly sorry for the delay! I haven’t been able to get to this yet. I suspect it’ll be hard for me to debug without having the data that was in the clipboard, but I’ll try!

**Comment by aviflax** [comment] 2018-07-31 00:58
@jabley sorry again for the egregious delay. I just opened #55 which fixes this bug — which was of course caused by me. You’re welcome to review the PR if you’d like, but it’s totally optional — my team should be able to get to it within ~12 hours and I suspect I’ll have it merged within ~24. And of course you can just try working with this branch if you’d like.

**Comment by aviflax** [comment] 2018-07-31 13:39
@jabley the fix is merged. I hope you’re able to try the tool out again!

**Closed** 2018-07-31 13:38 UTC
